In [ ]:
[Coding]:			
1. 
#    Finish 2D convolution/filtering by your self. 
#    What you are supposed to do can be described as "median blur", which means by using a sliding window 
#    on an image, your task is not going to do a normal convolution, but to find the median value within 
#    that crop.
#
#    You can assume your input has only one channel. (a.k.a a normal 2D list/vector)
#    And you do need to consider the padding method and size. There are 2 padding ways: REPLICA & ZERO. When 
#    "REPLICA" is given to you, the padded pixels are same with the border pixels. E.g is [1 2 3] is your
#    image, the padded version will be [(...1 1) 1 2 3 (3 3...)] where how many 1 & 3 in the parenthesis 
#    depends on your padding size. When "ZERO", the padded version will be [(...0 0) 1 2 3 (0 0...)]
#
#    Assume your input's size of the image is W x H, kernel size's m x n. You may first complete a version 
#    with O(W·H·m·n log(m·n)) to O(W·H·m·n·m·n)).
#    Follow up 1: Can it be completed in a shorter time complexity?
#
#    Python version:
#    def medianBlur(img, kernel, padding_way):
#        img & kernel is List of List; padding_way a string
#        Please finish your code under this blank

In [3]:
import cv2
import numpy as np
img = cv2.imread('lenna.jpg',0)
cv2.imshow('lenna',img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [21]:
import cv2
import numpy as np
fn="lenna.jpg"
myimg=cv2.imread(fn)
img=cv2.cvtColor(myimg,cv2.COLOR_BGR2GRAY)
 
#加上椒盐噪声
#灰阶范围
w=img.shape[1]
h=img.shape[0]
newimg=np.array(img)
#噪声点数量
noisecount=5000
for k in range(0,noisecount):
    xi=int(np.random.uniform(0,newimg.shape[1]))
    xj=int(np.random.uniform(0,newimg.shape[0]))
    newimg[xj,xi]=0
 
 
#滤波去噪
lbimg=cv2.medianBlur(newimg,3)
cv2.imshow('src',newimg)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()
cv2.imshow('dst',lbimg)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()      


In [20]:
import cv2
import numpy as np
fn="lenna.jpg"
myimg=cv2.imread(fn)
img=cv2.cvtColor(myimg,cv2.COLOR_BGR2GRAY)
 
#加上椒盐噪声
#灰阶范围
w=img.shape[1]
h=img.shape[0]
lbimg1=np.array(img)
#噪声点数量
noisecount=5000
for k in range(0,noisecount):
    xi=int(np.random.uniform(0,w))
    xj=int(np.random.uniform(0,h))
    img[xj,xi]=255
 
 
#滤波去噪
for y in range(1,h-1):
    for x in range(1,w-1):
        lbimg1[y,x]=np.median(img[y-1:y+2,x-1:x+2])
cv2.imshow('src1',img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()
cv2.imshow('dst1',lbimg1)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()      

In [47]:
np.pad?

In [46]:
import cv2
import numpy as np
fn="lenna.jpg"
myimg=cv2.imread(fn)
img=cv2.cvtColor(myimg,cv2.COLOR_BGR2GRAY)
img_pad1 = np.pad(img,((1,1),(1,1)),'constant',constant_values=(0,0))
print(img_pad1)
img_pad2 = np.pad(img,((1,1),(1,1)),'edge')
print(img_pad2)

[[  0   0   0 ...   0   0   0]
 [  0 172 172 ... 180 149   0]
 [  0 171 171 ... 185 156   0]
 ...
 [  0  22  31 ...  86  90   0]
 [  0  21  31 ...  96  98   0]
 [  0   0   0 ...   0   0   0]]
[[172 172 172 ... 180 149 149]
 [172 172 172 ... 180 149 149]
 [171 171 171 ... 185 156 156]
 ...
 [ 22  22  31 ...  86  90  90]
 [ 21  21  31 ...  96  98  98]
 [ 21  21  31 ...  96  98  98]]


In [50]:
import cv2
import numpy as np
fn="lenna.jpg"
myimg=cv2.imread(fn)
img=cv2.cvtColor(myimg,cv2.COLOR_BGR2GRAY)
img_pad = np.pad(img,((1,1),(1,1)),'constant',constant_values=(0,0))
#加上椒盐噪声
#灰阶范围
w=img_pad.shape[1]
h=img_pad.shape[0]
lbimg1=np.array(img_pad)
#噪声点数量
noisecount=5000
for k in range(0,noisecount):
    xi=int(np.random.uniform(0,w))
    xj=int(np.random.uniform(0,h))
    img_pad[xj,xi]=255

#滤波去噪
for y in range(1,h-1):
    for x in range(1,w-1):
        lbimg1[y,x]=np.median(img[y-1:y+2,x-1:x+2])
cv2.imshow('src1',img_pad)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()
cv2.imshow('dst1',lbimg1)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()      

In [29]:
a = np.array([[10, 7, 4], [3, 2, 1]])
print(a)
padding_a = np.array([[0,0,0,0,0],[0,10,7,4,0],[0,3,2,1,0],[0,0,0,0,0]])
print(padding_a)

[[10  7  4]
 [ 3  2  1]]
[[ 0  0  0  0  0]
 [ 0 10  7  4  0]
 [ 0  3  2  1  0]
 [ 0  0  0  0  0]]


In [16]:
np.median?

In [25]:
import cv2
import numpy as np
fn="lenna.jpg"
myimg=cv2.imread(fn)
img=cv2.cvtColor(myimg,cv2.COLOR_BGR2GRAY)
print(x,y)
print(img[y-1:y+2,x-1:x+2])
print(np.median(img[y-1:y+2,x-1:x+2]))

218 218
[[55 70 76]
 [73 86 90]
 [85 96 98]]
85.0


In [59]:
import cv2
import numpy as np
img = cv2.imread('lenna.jpg',0)
cv2.imshow('lenna',img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()  
img_pad0 = np.pad(img,((1,1),(1,1)),'constant',constant_values=(0,0))
w=img_pad0.shape[1]
h=img_pad0.shape[0]
lbimg0=np.array(img_pad0)
#噪声点数量
noisecount=500
for k in range(0,noisecount):
    xi=int(np.random.uniform(0,w))
    xj=int(np.random.uniform(0,h))
    img_pad0[xj,xi]=255
for y in range(1,h-1):
    for x in range(1,w-1):
        lbimg0[y,x]=np.median(img_pad0[y-1:y+2,x-1:x+2])
print(lbimg0)
lb_w = lbimg0.shape[1]
lb_h = lbimg0.shape[0]
lbimg = lbimg0[1:lb_w-1,1:lb_h-1 ]
print(lbimg)
cv2.imshow('img_pad0',img_pad0)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()
cv2.imshow('lbimg0',lbimg0)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()
cv2.imshow('lbimg',lbimg)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows() 

[[  0   0   0 ...   0   0   0]
 [  0   0 171 ... 156   0   0]
 [  0 169 171 ... 156 119   0]
 ...
 [  0  22  29 ...  85  76   0]
 [  0   0  22 ...  85   0   0]
 [  0   0   0 ...   0   0   0]]
[[  0 171 170 ... 131 156   0]
 [169 171 170 ... 140 156 119]
 [167 169 168 ... 130 119  28]
 ...
 [ 25  29  30 ...  57  70  70]
 [ 22  29  30 ...  73  85  76]
 [  0  22  29 ...  73  85   0]]
